#!/bin/bash

# /usr/bin/iiab-remote-off is intended to fully turn off multiple remote
# support services like OpenVPN and others, to reduce risk of remote attacks.

# Do nothing if OpenVPN not installed
which openvpn
if [ $? -ne 0 ]; then
    echo 'Cannot find the OpenVPN program (openvpn).'
    exit 1
fi

systemctl disable openvpn
systemctl stop openvpn

sleep 5
ps -e | grep vpn
if [ $? -eq 0 ]; then
    echo OpenVPN failed to stop.
else
    echo Successfully stopped and disabled OpenVPN.
fi
