#!/bin/bash
# if the wan has recently come up, see if we need to start openvpn
systemctl is-enabled openvpn
if [ $? -eq 0 ]; then
   pgrep openvpn
   if [ $? -ne 0 ]; then
      systemctl start openvpn@xscenet
   fi
fi
