#!/bin/bash
# Not really used as of August 2018, but perhaps can be revived for CentOS etc

# If the wan has recently come up, see if we need to start openvpn

systemctl is-enabled openvpn
if [ $? -eq 0 ]; then
    pgrep openvpn
    if [ $? -ne 0 ]; then
        systemctl start openvpn@xscenet
    fi
fi
