#!/bin/bash
# script to write a handle file that identifies the openvpn client to server
echo
echo
read -p "what identifying handle would you like to use? " ans
if [ "$ans" == "" ]; then
  if [ -f /etc/xsce/handle ]; then
    rm -f /etc/xsce/handle
  fi
else
  echo $ans > /etc/xsce/handle 
fi
{{ systemctl_program }} restart openvpn@xscenet
