#!/bin/bash
# fetch the world to zoom 10 without Admin Console

source_url=https://archive.org/download
sat=$source_url/satellite_z0-z9_v3.mbtiles/satellite_z0-z9_v3.mbtiles
working_dir=/library/working/maps
planet2z10=https://archive.org/download/osm-planet_z0-z10_2019.mbtiles/osm-planet_z0-z10_2019.mbtiles
san_jose2z14=https://archive.org/download/san_jose_z11-z14_2019.mbtiles/san_jose_z11-z14_2019.mbtiles

# get the data for planet to zoom 10, satellite to zoom 9, and san_jose to zoom 14
fn=$(basename $sat)
if [ ! -f /library/www/osm-vector-maps/viewer/tiles/$fn ];then
   wget -c $sat -P $working_dir
fi
fn=$(basename $planet2z10)
if [ ! -f /library/www/osm-vector-maps/viewer/tiles/$fn ];then
   wget -c $planet2z10 -P $working_dir
fi
fn=$(basename $san_jose2z14)
if [ ! -f /library/www/osm-vector-maps/viewer/tiles/$fn ];then
   wget -c $san_jose2z14 -P $working_dir
fi

# Just move the downloaded data files and blast any conflicting files away
if [ ! -z  "$(ls -A /library/working/maps)" ]; then
   mv -f /library/working/maps/* /library/www/osm-vector-maps/viewer/tiles/
fi

# put a json file which initializes the map view
cp /opt/iiab/iiab/roles/osm-vector-maps/files/init.json /library/www/osm-vector-maps/viewer/
