#!/bin/bash -x
# fetch the specified tileset or world to zoom 10 without Admin Console

source_url=https://archive.org/download
SATELLITE=satellite_z0-z9_v3.mbtiles
working_dir=/library/working/maps
PLANET=osm-planet_z0-z10_2019.mbtiles
SAN_JOSE=osm_san_jose_z11-z14_2019.mbtiles

# If called without a parameter (perhaps from ansible), just load world to zoom 10
if [ $# -eq 0 ]; then
   TILESET=$SAN_JOSE
   PROGRESS=""
   fn=$(basename $SAN_JOSE)
   if [ ! -f /library/www/osm-vector-maps/viewer/tiles/$fn ];then
      wget -c $source_url/$SAN_JOSE/$SAN_JOSE $PROGRES -P $working_dir
   fi
   if [ $? -ne 0 ]; then
      echo "Download of $fn failed. Please retry download command"
      exit 1
   fi
else
   TILESET=$1
   PROGRESS="--progress=dot:giga"
   fn=$(basename $1)
   if [ ! -f /library/www/osm-vector-maps/viewer/tiles/$fn ];then
      wget -c $source_url/$1/$1 $PROGRES -P $working_dir
   fi
   if [ $? -ne 0 ]; then
      echo "Download of $fn failed. Please retry download command"
      exit 1
   fi
fi

# get the data for planet to zoom 10, satellite to zoom 9, and san_jose to zoom 14
fn=$(basename $SATELLITE)
if [ ! -f /library/www/osm-vector-maps/viewer/tiles/$fn ];then
   wget -c $source_url/$SATELLITE/$SATELLITE $PROGRES -P $working_dir
fi
if [ $? -ne 0 ]; then
   echo "Download of $fn failed. Please retry download command"
   exit 1
fi

fn=$(basename $PLANET)
if [ ! -f /library/www/osm-vector-maps/viewer/tiles/$fn ];then
   wget -c $source_url/$PLANET/$PLANET $PROGRES -P $working_dir
fi
if [ $? -ne 0 ]; then
   echo "Download of $fn failed. Please retry download command"
   exit 1
fi


# Just move the downloaded data files and blast any conflicting files away
if [ ! -z  "$(ls -A $working_dir)" ]; then
   mv -f $working_dir/*.mbtiles /library/www/osm-vector-maps/viewer/tiles/
fi

# put a json file which initializes the map view
cp /opt/iiab/iiab/roles/osm-vector-maps/files/init.json /library/www/osm-vector-maps/viewer/
