# Self-hosted Anki-compatible sync server
#
# anki_install: False
# anki_enabled: False
# anki_url: /anki
# anki_port: 27701
# anki_home: "{{ content_base }}/anki-sync"
# anki_sync_users:
#   - anki:changeme
#
# All above are set in: github.com/iiab/iiab/blob/master/vars/default_vars.yml
# If nec, change them by editing /etc/iiab/local_vars.yml prior to installing!

anki_version: latest
anki_venv: /opt/iiab/anki-sync
anki_user: root
anki_package_spec: "{{ 'anki' if anki_version == 'latest' else 'anki==' ~ anki_version }}"
