#!/bin/bash
if [ "$IFACE" == "{{ discovered_wireless_iface }}" ]; then
    echo "NET-DISP-WiFi $IFACE $STATE"
    # If we are here we have a dhcp ip address
    CHAN=`iw $IFACE info|grep channel|cut -d' ' -f2`
    echo "Using channel $CHAN for carrier"
    HOSTAPD=`grep channel /etc/hostapd/hostapd.conf | awk -F = '{print $2}'`
    echo "Hostapd set for $HOSTAPD"
    if [ $CHAN -ne $HOSTAPD ] && [ $CHAN -lt 14 ]; then
        echo "Editing Hostapd for channel $CHAN"
        cp /etc/hostapd/hostapd.conf.iiab /etc/hostapd/hostapd.conf
        sed -i -e "s/^channel.*/channel=$CHAN/" /etc/hostapd/hostapd.conf
        systemctl stop wpa_supplicant
        systemctl restart hostapd
        systemctl start wpa_supplicant
    else
        echo "Upstream Channel greater than 13 or is the same - not changing hostapd.conf"
    fi
    sleep 3
    /usr/sbin/ip link set ap0 up
fi
