#!/bin/bash

INVENTORY=ansible_hosts
PLAYBOOK=check-vars.yml

CWD=`pwd`
if [ ! -f $PLAYBOOK ]; then
    echo "Exiting: IIAB Playbook not found."
    echo "Please run this in /opt/iiab/iiab (top level of the git repo)."
    exit 1
fi
Start=`date`
ansible-playbook -i $INVENTORY $PLAYBOOK --connection=local
End=`date`
echo "check-vars run end:   $End"
echo "check-vars run start: $Start"

