#!/bin/bash

INVENTORY=ansible_hosts
PLAYBOOK=validate-vars.yml
LOG=check-vars.log
CWD=`pwd`
if [ ! -f $PLAYBOOK ]; then
    echo "Exiting: IIAB Playbook not found."
    echo "Please run this in /opt/iiab/iiab (top level of the git repo)."
    exit 1
fi

export ANSIBLE_LOG_PATH="$CWD"/"$LOG"

if [ -f $LOG ]; then
   rm $LOG
fi

Start=`date`
ansible-playbook -i $INVENTORY $PLAYBOOK --connection=local
End=`date`
echo "check-vars run end:   $End"
echo "check-vars run start: $Start"

if [ $(grep failed $LOG | wc -l) -gt 1 ]; then
    echo "local_vars.yml contains errors, please check the entries listed below"
    grep failed $LOG
else
    echo "local_vars.yml seems fine, continuing"
fi
