#!/bin/bash
if [ ! -f iiab-network.yml ]
then
 echo "XSCE Playbook not found."
 echo "Please run this command from the top level of the git repo."
 echo "Exiting."
 exit
fi

if [ ! -f /etc/iiab/iiab.ini ]
then
  echo "IIAB not installed please run ./runansible first"
  exit
fi

if [ ! -f /etc/iiab/config_vars.yml ]
then
   touch /etc/iiab/config_vars.yml
fi

export ANSIBLE_LOG_PATH="$XSCE_DIR/iiab-network.log"
ansible-playbook -i ansible_hosts iiab-network.yml --connection=local
echo "" >> iiab-network.log
ls -la /etc/sys*/net*/ifcfg* >> iiab-network.log
if [ ! "OS" == "debian" ]; then
   nmcli d >> iiab-network.log
   nmcli c >> iiab-network.log
fi
brctl show >> iiab-network.log
echo "run on:" >> iiab-network.log
date >> iiab-network.log
echo "" >> iiab-network.log
echo "" >> iiab-network.log
