#!/bin/bash

INVENTORY="ansible_hosts"
PLAYBOOK="iiab-from-cmdline.yml"
CWD=`pwd`
APPS=/etc/iiab/config_vars2.yml
if [ ! -f $PLAYBOOK ]; then
    echo "Exiting: IIAB Playbook not found."
    echo "Please run this in /opt/iiab/iiab (top level of the git repo)."
    exit 1
fi
if grep -q sugar $APPS; then
    if ! grep -q mongodb $APPS; then
        echo "mongodb_installed: True" >> $APPS
    fi
fi

export ANSIBLE_LOG_PATH="$CWD/iiab-configure.log"
ansible-playbook -i $INVENTORY $PLAYBOOK --connection=local
