#!/bin/bash

INVENTORY="ansible_hosts"
PLAYBOOK="iiab-from-console.yml"
CWD=`pwd`
if [ ! -f $PLAYBOOK ]; then
    echo "Exiting: IIAB Playbook not found."
    echo "Please run this in /opt/iiab/iiab (top level of the git repo)."
    exit 1
fi
export ANSIBLE_LOG_PATH="$CWD/iiab-configure.log"
ansible-playbook -i $INVENTORY $PLAYBOOK --connection=local
