#!/bin/bash

PLAYBOOK="iiab-support.yml"
INVENTORY="ansible_hosts"
CWD=`pwd`

export ANSIBLE_LOG_PATH="$CWD/iiab-install.log"

if [ ! -f $PLAYBOOK ]; then
    echo -e "\nEXITING: $PLAYBOOK not found.\n"
    echo -e "Please run this command from /opt/iiab/iiab (top of git repo).\n"
    exit 1
fi

echo -en "\n\nWhat OpenVPN machine name (openvpn_handle) do you want? "
read ans < /dev/tty
if [ "$ans" != "" ]; then
    sed -i -e "s/^openvpn_handle:.*/openvpn_handle: $ans/" /etc/iiab/local_vars.yml
    echo -e "\nYour machine's openvpn_handle is now set, in /etc/iiab/local_vars.yml\n"
else
    echo -e "\nWARNING: openvpn_handle remains unchanged in /etc/iiab/local_vars.yml\n"
fi

sed -i -e "s/^openvpn_install:.*/openvpn_install: True/" /etc/iiab/local_vars.yml
sed -i -e "s/^openvpn_enabled:.*/openvpn_enabled: True/" /etc/iiab/local_vars.yml

echo -e "Now let's (re)install and activate OpenVPN...\n"

ansible-playbook -i $INVENTORY $PLAYBOOK --connection=local

echo -en "\nYour OpenVPN handle is....... "
cat /etc/iiab/openvpn_handle
echo -e "\nYour OpenVPN IP address is... $(ip a | grep tun0$ | awk '{print $2}')\n\n"
