#!/bin/bash

INVENTORY=ansible_hosts
PLAYBOOK=run-roles-tmp.yml

CWD=`pwd`
if [ ! -f iiab-stages.yml ]; then
    echo "Exiting: IIAB Playbook not found."
    echo "Please run this in /opt/iiab/iiab (top level of the git repo)."
    exit 1
fi

if [[ $# -eq 0 ]] ; then
    echo "Usage: ./runroles <list of roles separated by spaces>"
    exit 0
fi

# Everything else needs to be run as root
if [ $(id -u) -ne 0 ]; then
    echo -e "'runroles' must be run as root. Try 'sudo runroles'\n"
    exit 1
fi


# make working playbook
cp runroles-base.yml $PLAYBOOK

# add desired roles from arguments
for role in "$@"
do
    echo "    - { role: $role }" >> $PLAYBOOK
done

ansible-playbook -i $INVENTORY $PLAYBOOK --connection=local
