#!/bin/bash
if [ ! -f /etc/iiab/iiab.env ]
then
   echo "IIAB not installed please run ./runansible first"
   exit
fi

if [ ! -f iiab.yml ]
then
 echo "XSCE Playbook not found."
 echo "Please run this command from the top level of the git repo."
 echo "Exiting."
 exit
fi

tags=$(echo $1 | tr "," "\n")

found="N"

for tag in $tags
do
  if [ "$tag" == "prep" ]
  then
    found="Y"
  fi

done

# echo $found

taglist=$1

if [ "$found" == "N" ]
then
  taglist="vars,"$taglist
fi

# script to run a specific tag in the current playbook
if [ $# -ne 1 ]; then
	echo "usage: $0 <tagname>"
	echo
	echo " If you would like a list of possible values, enter $0 XXX"
	exit 1
fi
export ANSIBLE_LOG_PATH="$XSCE_DIR/iiab-debug.log"
ansible-playbook -i ansible_hosts iiab.yml --connection=local --tags="""$taglist"""
