#!/bin/bash

if [ -f /etc/xsce/xsce.env ]
then
  . /etc/xsce/xsce.env
  cd $XSCE_DIR
else
  echo /etc/xsce/xsce.env is missing. Playbook has not been run.
  exit 1
fi

if [ ! -f xsce-network.yml ]
then
 echo "XSCE Playbook not found."
 echo "Please run this command from the top level of the git repo."
 echo "Exiting."
 exit
fi

if [ ! -f /etc/xsce/config_vars.yml ]
then
   touch /etc/xsce/config_vars.yml
fi

export ANSIBLE_LOG_PATH="$XSCE_DIR/xsce-network.log"
ansible-playbook -i ansible_hosts xsce-network.yml --connection=local
echo "" >> xsce-network.log
ls -la /etc/sys*/net*/ifcfg* >> xsce-network.log
if [ ! "OS" == "debian" ]; then
   nmcli d >> xsce-network.log
   nmcli c >> xsce-network.log
fi
brctl show >> xsce-network.log
echo "run on:" >> xsce-network.log
date >> xsce-network.log
echo "" >> xsce-network.log
echo "" >> xsce-network.log
