- name: Make serving directory (0755 by default)
  file:
    path: "{{ maps_dot_black_path }}"
    state: directory
    # mode: 0755

- name: Make index file
  copy:
    src: "files/index.html"
    dest: "{{ maps_dot_black_path }}/index.html"

- name: Download all the basic maps.black javascript and styles (0755)
  get_url:
    url: "{{ maps_dot_black_resources_url }}/{{ item }}"
    dest: "{{ maps_dot_black_path }}"
    mode: "0755"
    timeout: "{{ download_timeout }}"
  with_items:
    - resourcetiles-minimal.pmtiles
    - maps.black.js
    - maps.black-component.js
    - resourcetiles-minimal.pmtiles

- name: Download a low resolution base map (0755)
  get_url:
    url: "{{ maps_dot_black_assets_url }}/{{ item.filename }}"
    dest: "{{ maps_dot_black_path }}"
    checksum: "{{ item.checksum }}" # Avoid repeated downloads of this big file
    mode: "0755"
    timeout: "{{ download_timeout }}"
  with_items:
    - "{{ maps_dot_black_tiles.naturalearth_openmaptiles }}"
    - "{{ maps_dot_black_tiles.naturalearth6_NE2_HR_SR_W_DR_WEBP }}"

- name: "Set 'maps_dot_black_installed: True'"
  set_fact:
    maps_dot_black_installed: True

- name: "Add 'maps_dot_black_installed: True' to {{ iiab_state_file }}"
  lineinfile:
    path: "{{ iiab_state_file }}"    # /etc/iiab/iiab_state.yml
    regexp: '^maps_dot_black_installed'
    line: 'maps_dot_black_installed: True'
