### maps.black ###

- name: Make serving directory (0755 by default)
  file:
    path: "{{ maps_dot_black_serve_path }}"
    state: directory
    # mode: 0755

- name: Make index file
  copy:
    src: "files/index.html"
    dest: "{{ maps_dot_black_serve_path }}/index.html"

- name: Download all the basic maps.black javascript and styles (0644)
  get_url:
    url: "{{ maps_dot_black_small_assets_url }}/{{ item.filename }}"
    dest: "{{ maps_dot_black_serve_path }}"
    checksum: "{{ item.checksum }}" # Avoid repeated downloads
    mode: "0644"
    timeout: "{{ download_timeout }}"
  with_items: "{{ maps_dot_black_js_and_styles }}"

- name: Download map tiles (0644)
  get_url:
    url: "{{ maps_dot_black_tiles_url }}/{{ item.filename }}"
    dest: "{{ maps_dot_black_serve_path }}"
    checksum: "{{ item.checksum }}" # Avoid repeated downloads (especially for these big files)
    mode: "0644"
    timeout: "{{ download_timeout }}"
  when: item.included
  with_items: "{{ maps_dot_black_tiles }}"

- name: Make maps_2 directory (0755 by default)
  file:
    path: "{{ maps_2_data_root }}"
    state: directory
    # mode: 0755

- name: "Set 'maps_dot_black_installed: True'"
  set_fact:
    maps_dot_black_installed: True

### Photon ###

# I would like to download the archive, check the checksum, and extract it.
# AND, I would like to not repeat this if it's already done.
# However, there's no module that does both checksum and extract, so we have
# to construct it ourselves.

- name: Check if photon is already downloaded
  stat:
    path: "{{ photon_marker }}"
  register: photon_already_downloaded

# Doing get_url / unarchive separately because I want checksum
- name: Download photon data
  get_url:
    url: "{{ photon_data_url }}/{{ photon_data.filename }}"
    dest: "{{ maps_2_data_root }}/{{ photon_data.filename }}"
    checksum: "{{ photon_data.checksum }}"
    timeout: "{{ download_timeout }}"
  when: photon_data.included and (not photon_already_downloaded.stat.exists)

- name: Extract photon data
  unarchive:
    src: "{{ maps_2_data_root }}/{{ photon_data.filename }}"
    dest: "{{ photon_data_path }}"
    remote_src: yes
  when: photon_data.included and (not photon_already_downloaded.stat.exists)

- name: Delete photon archive
  file:
    path: "{{ maps_2_data_root }}/{{ photon_data.filename }}"
    state: absent

- name: Set marker to say photon database has been installed
  file:
    path: "{{ photon_marker }}"
    state: touch

### Finish ###

- name: "Add 'maps_dot_black_installed: True' to {{ iiab_state_file }}"
  lineinfile:
    path: "{{ iiab_state_file }}"    # /etc/iiab/iiab_state.yml
    regexp: '^maps_dot_black_installed'
    line: 'maps_dot_black_installed: True'
