- name: Assert that "maps_dot_black_install is sameas true" (boolean not string etc)
  assert:
    that: maps_dot_black_install is sameas true
    fail_msg: "PLEASE SET 'maps_dot_black_install: True' e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that "maps_dot_black_enabled | type_debug == 'bool'" (boolean not string etc)
  assert:
    that: maps_dot_black_enabled | type_debug == 'bool'
    fail_msg: "PLEASE GIVE VARIABLE 'maps_dot_black_enabled' A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes


- block:

    - name: Install maps.black if 'maps_dot_black_installed' not defined, e.g. in {{ iiab_state_file }}    # /etc/iiab/iiab_state.yml
      include_tasks: install.yml
      when: maps_dot_black_installed is undefined

    - name: Enable/Disable/Reload NGINX for maps.black, if nginx_enabled
      include_tasks: nginx.yml

    - name: Add 'maps-dot-black' variable values to {{ iiab_ini_file }}
      ini_file:
        path: "{{ iiab_ini_file }}"    # /etc/iiab/iiab.ini
        section: maps-dot-black
        option: "{{ item.option }}"
        value: "{{ item.value | string }}"
      with_items:
        - option: name
          value: maps.black
        - option: description
          value: 'amirite'
        - option: maps_dot_black_install
          value: "{{ maps_dot_black_install }}"
        - option: maps_dot_black_enabled
          value: "{{ maps_dot_black_enabled }}"

  rescue:

    - name: 'SEE ERROR ABOVE (skip_role_on_error: {{ skip_role_on_error }})'
      fail:
        msg: ""
      when: not skip_role_on_error
