- name: Enable http://box/maps & http://box/maps-dot-black via NGINX, by installing {{ nginx_conf_dir }}/maps-dot-black-nginx.conf from template
  template:
    src: maps-dot-black-nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/maps-dot-black-nginx.conf"    # /etc/nginx/conf.d

- name: Reload 'nginx' systemd service
  systemd:
    name: nginx
    state: reloaded
