#!/bin/bash

tailscale down

echo -e "\n\e[44;1mDisconnecting from VPN...\e[0m\n"
echo -e "\e[4mTo permanently log out of VPN:\e[0m\n"    # Expires machine node key, from /var/lib/tailscale/tailscaled.state
echo -e "    tailscale logout\n"                        # ...as seen by 'tailscale status --json' (related: 'tailscale debug prefs')
