#!/usr/bin/python

import zmq
import sys

REQUEST_TIMEOUT = 10000

if  len(sys.argv) == 1 or len(sys.argv) > 3:
  print 'usage: cmdsrv-ctl "<command>" "<optional json argument>"'
  sys.exit(0)

cmd = sys.argv[1]
send_msg = cmd

if  len(sys.argv) == 3:
    cmd_args = sys.argv[2]
    send_msg += ' ' +  cmd_args

print "message to send: ", send_msg

ipc_sock = "/run/cmdsrv_sock"

context = zmq.Context()
print "Connecting to server..."
socket = context.socket(zmq.DEALER)
socket.connect ("ipc://%s" % ipc_sock)
poll = zmq.Poller()
poll.register(socket, zmq.POLLIN)

socket.send (send_msg)

socks = dict(poll.poll(REQUEST_TIMEOUT))

if socket in socks and socks[socket] == zmq.POLLIN:
#if socket_poll.get(socket) == zmq.POLLIN:
    #  Get the reply
    reply_msg = socket.recv()
else:
    reply_msg = '{"Error": "No Response from XSCE-CMDSRV"}'

socket.setsockopt(zmq.LINGER, 0)
socket.close()
poll.unregister(socket)

print "Received reply: ", reply_msg
