# This is the default location where the kalite command finds its settings
# You can change the below lines to use different default settings or
# you can run kalite <command> --settings=other_module

from kalite.project.settings.base import *

# from kalite.project.settings.dev import *
# from kalite.project.settings.raspberry_pi import *

# Put your custom settings here
# MY_SETTING = 123
 
#Generated by IIAB
#NGINX is on port 8008 and expects ka-lite on port 7007
PRODUCTION_PORT=7007

#Persist ka-lite django page cache between reboots
CACHE_LOCATION = '/var/tmp/kalite/cache'

#Optimise cherrypy server for Raspberry Pi
CHERRYPY_THREAD_COUNT = 20

