#!/bin/bash -xe

# Run 'sudo iiab-remoteit-off' to disable remote.it on this IIAB. GENERAL TIPS:
# http://FAQ.IIAB.IO -> "How can I remotely manage my Internet-in-a-Box?"

# GUIDE: https://github.com/iiab/iiab/blob/master/roles/remoteit/README.md

# FYI 'remoteit' Device Package AND /usr/bin/remoteit CLI are installed by:
# https://github.com/iiab/iiab/blob/master/roles/remoteit/tasks/install.yml

if grep -q '^remoteit_enabled:' /etc/iiab/local_vars.yml; then
    sed -i "s/^remoteit_enabled:.*/remoteit_enabled: False/" /etc/iiab/local_vars.yml
else
    echo "remoteit_enabled: False" >> /etc/iiab/local_vars.yml
fi

# remote.it "parent" service
systemctl stop connectd
systemctl disable connectd

# "Remote tcp command service"
systemctl stop schannel
systemctl disable schannel

# "Remote tcp connection service"
systemctl stop $(ls /etc/systemd/system/multi-user.target.wants/ | grep remoteit@)
systemctl disable $(ls /etc/systemd/system/multi-user.target.wants/ | grep remoteit@)
# Its systemd service name (e.g. remoteit@80:00:01:7F:7E:00:56:36.service)
# changes when a new claim code is generated!
