#!/bin/bash

# Run 'sudo iiab-remoteit' to (re)install remoteit without hassle.  GENERAL TIPS:
# http://FAQ.IIAB.IO -> "How can I remotely manage my Internet-in-a-Box?"

echo -e "Now let's (re)enable remoteit...\n"
if grep -q '^remoteit_enabled:' /etc/iiab/local_vars.yml; then
    sed -i "s/^remoteit_enabled:.*/remoteit_enabled: True/" /etc/iiab/local_vars.yml
else
    echo "remoteit_enabled: True" >> /etc/iiab/local_vars.yml
fi

echo -e "Plz wait a few minutes as remoteit is confirmed/installed...\n"
if grep -q '^remoteit_install:' /etc/iiab/local_vars.yml; then
    sed -i "s/^remoteit_install:.*/remoteit_install: True/" /etc/iiab/local_vars.yml
else
    echo "remoteit_install: True" >> /etc/iiab/local_vars.yml
fi

if [ -d /opt/iiab/iiab ]; then
    cd /opt/iiab/iiab
    ./runrole remoteit
    echo
else
    echo -e " \e[41;1m       Directory /opt/iiab/iiab does not exist: CANNOT INSTALL REMOTEIT!       \e[0m\n"
    exit 1
fi
