#!/bin/bash -x
sudo -u {{ apache_user }} /usr/bin/php {{ moodle_base }}/admin/cli/install.php \
--wwwroot=http://{{ iiab_hostname }}.{{ iiab_domain }}/moodle --dataroot={{ moodle_data }} \
--dbtype=pgsql --dbname={{ moodle_database_name }} --dbuser=Admin --dbpass=changeme \
--fullname=Your_School --shortname=School \
--adminuser=Admin --adminpass=changeme \
--non-interactive --agree-license
chown {{ apache_user }}:{{ apache_user }} {{ moodle_base }}/config.php
