#!/bin/bash -x
sudo -u {{ apache_data }} /usr/bin/php {{ moodle_base }}/admin/cli/install.php \
--wwwroot=http://{{ xsce_hostname }}.{{ xsce_domain }}/moodle --dataroot={{ moodle_data }} \
--dbtype=pgsql --dbname={{ moodle_database_name }} --dbuser=Admin --dbpass=changeme \
--fullname=Your_School --shortname=School \
--adminuser=admin --adminpass=changeme \
--non-interactive --agree-license
chown {{ apache_data }}:{{ apache_data }} {{ moodle_base }}/config.php
