#!/bin/bash
sed -i -e "s/^denyinterfaces/#denyinterfaces/" /etc/dhcpcd.conf
systemctl disable hostapd
systemctl stop hostapd
systemctl disable dhcpd
systemctl stop dhcpd
systemctl daemon-reload
systemctl restart dhcpcd
systemctl restart networking

# Experimental/Temporary workaround for WiFi "10SEC disease"
# https://github.com/iiab/iiab/issues/638#issuecomment-355455454
if grep -qi raspbian /etc/*release; then ip link set dev wlan0 promisc on; fi
