#!/bin/bash

{% if wifi_up_down %}
echo "Iiab-hotspot-up/down only functions when /etc/iiab/wifi_up_down is set to False"
echo "  If you want hotspot on/off functions, please set wifi_up_down to False in /etc/iiab/local_vars.yml and run /opt/iiab/iiab/iiab-network"
exit 0

{% else %}
# hotspot-off before ap0_updown
sed -i -e "s/^denyinterfaces/#denyinterfaces/" /etc/dhcpcd.conf
systemctl disable hostapd
systemctl stop hostapd
#systemctl disable dnsmasq
#systemctl stop dnsmasq
systemctl daemon-reload
systemctl restart dhcpcd
#systemctl restart networking 6/15/2019 TFM removed

# Temporary promiscuous-mode workaround for RPi's WiFi "10SEC disease"
# Set wlan0 to promiscuous when AP's OFF (for possible WiFi gateway)
# SEE ALSO iiab-hotspot-on + /usr/libexec/iiab-startup.sh
# https://github.com/iiab/iiab/issues/638#issuecomment-355455454
if grep -qi raspbian /etc/*release; then
    ip link set dev wlan0 promisc on
fi
{% endif %}

sed -i -e "s/^HOSTAPD_ENABLED.*/HOSTAPD_ENABLED=False/" {{ iiab_env_file }}
