#!/bin/bash
sed -i -e "s/#denyinterfaces*/denyinterfaces/" /etc/dhcpcd.conf
systemctl enable hostapd
systemctl daemon-reload
systemctl restart dhcpcd
systemctl restart networking
systemctl start hostapd
