#!/bin/bash
cp -f /etc/hostapd/hostapd.conf.iiab /etc/hostapd/hostapd.conf
sed -i -e "s/#denyinterfaces*/denyinterfaces/" /etc/dhcpcd.conf
systemctl enable hostapd
systemctl enable dhcpd
systemctl daemon-reload
systemctl restart dhcpcd
systemctl restart networking
systemctl start hostapd
systemctl start dhcpd
