#!/bin/bash
sed -i -e "s/^denyinterfaces/#denyinterfaces/" /etc/dhcpcd.conf
systemctl disable hostapd
systemctl stop hostapd
systemctl disable dhcpd
systemctl stop dhcpd
systemctl daemon-reload
systemctl restart dhcpcd
systemctl restart networking

# Temporary promiscuous-mode workaround for RPi's WiFi "10SEC disease"
# Set wlan0 to promiscuous when needed as gateway (i.e. AP's OFF)
# SEE ALSO iiab-hotspot-on + /usr/libexec/iiab-startup.sh
# https://github.com/iiab/iiab/issues/638#issuecomment-355455454
if grep -qi raspbian /etc/*release; then
    ip link set dev wlan0 promisc on
    sed -i -e "s/hostapd_enabled.*/hostapd_enabled = False/" /etc/iiab/iiab.ini
fi
