<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.2.7.1 setup script
 * Date: Wed, 27 Aug 2014 04:06:59 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: School Server Mysql Database [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'School Server Mysql Database';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '/var/run/mysqld/mysqld.sock';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '53fd593a363ed4.99753154';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>

