#!/bin/bash

CMDSRV_SCRIPTS="{{ cmdsrv_dir }}/scripts"
if [ ! -f "$CMDSRV_SCRIPTS/iiab_update_menus.py" ]; then
  echo "Admin Console not installed. Exiting."
  exit
fi

$CMDSRV_SCRIPTS/iiab_update_menus.py

if [ $? -ne 0 ]; then
  echo "Update Menus Failed."
  exit 1
fi
exit
