#!/bin/bash

CMDSRV_SCRIPTS="/opt/admin/cmdsrv/scripts"
if [ ! -f "$CMDSRV_SCRIPTS/iiab-update-map.py" ]; then
  echo "Admin Console not installed. Exiting."
  exit
fi

$CMDSRV_SCRIPTS/iiab-update-map.py

if [ $? -ne 0 ]; then
  echo "Update Menus Failed."
  exit 1
fi
exit
