#!/bin/bash
# Remount usbdrive umask 0000 when KOLIBRI_DATA is present
# Mar 21, 2021
# by Jerry Vonau jvonau3@gmail.com

if [ -d "$UM_MOUNTPOINT/KOLIBRI_DATA" ]; then
            logger -p user.notice -t "71-kolibri" -- "KOLIBRI_DATA found Remounting mask=0000"
            umount $UM_MOUNTPOINT
            mount /$UM_DEVICE -o sync,noexec,nodev,noatime,nodiratime,umask=0000 $UM_MOUNTPOINT
else
    logger -p user.notice -t "71-kolibri" -- "Directory /KOLIBRI_DATA not found on USB"
fi
exit 0
