- vars:
    catalog_file_path: "{{ maps_catalog[catalog_item][catalog_item_variant | string] | default('') }}"
    catalog_file_name: "{{ catalog_file_path | split('/') | last }}"

    # How it's saved. Either a file or a directory.
    dest_name: "{{ catalog_file_name[:-7] if is_archive | default(false) else catalog_file_name }}"

  block:
    - name: "Make sure archives end in .tar.gz as expected"
      assert:
        that: (not (is_archive | default(false))) or catalog_file_name[-7:] == ".tar.gz"
        fail_msg: "Error: expect download file name to end in .tar.gz when is_archive=true"
        quiet: yes

    - name: "Make sure {{ catalog_item_variant_name }} has a valid value"
      assert:
        that: catalog_file_path != ""
        fail_msg: "Error: {{ catalog_item_variant_name }} is set to an invalid value (\"{{ catalog_item_variant }}\"). See `\"{{ catalog_item_variant_name }}\"` in https://github.com/iiab/iiab/blob/master/roles/maps/generate-catalog.py for valid values."
        quiet: yes

    - name: "Check if we already have {{ catalog_file_path }} possibly with a different date"
      shell: |
        import glob, os

        new_file_name = "{{ dest_name }}"
        new_file_name_parts = new_file_name.split('.')

        if len(new_file_name_parts) not in [3, 4]:
            # TODO - we need to fix terrarium-none.pmtiles to conform to this
            print ("unexpected_name")
            print ("Unexpected file name:", new_file_name)
        else:
            if len(new_file_name_parts) == 4:
                file_type, _date, file_depth, extension = new_file_name_parts
                glob_test = f"*.*.{file_depth}.{extension}"
            elif len(new_file_name_parts) == 3:
                file_type, _date, file_depth = new_file_name_parts
                glob_test = f"*.*.{file_depth}"

            if len(glob.glob(os.path.join("{{ dest_base_path }}", glob_test))) > 0:
                print ("existing_file")
            else:
                print ("ok")
      args:
        executable: /usr/bin/python3

      register: file_upgrade

    - name: "Check for unexpected file name in catalog"
      fail:
          msg: "{{ file_upgrade.stdout_lines.1 }}"
      when: file_upgrade.stdout_lines|length != 0 and file_upgrade.stdout_lines.0 == "unexpected_name"

    - when: file_upgrade.stdout_lines|length != 0 and file_upgrade.stdout_lines.0 == "ok"
      block:
        - name: "Download {{ catalog_item }} from catalog"
          include_tasks: download_large_file.yml
          vars:
            item: "{{ catalog_file_path }}"
       
        # TODO actually be careful - in the end we want to make sure the correct symlink is set no matter the input scenario
        - name: "Select {{ catalog_item }}"
          file:
            src: "{{ dest_base_path }}/{{ dest_name }}"
            path: "{{ dest_base_path }}/{{ symlink_name }}"
            state: link
