# TODO - What if the catalog upgrades, but people re-run and don't want to upgrade global data? Maybe stop if they have data, even if it's old? Add a "quick tip" to delete it first, to allow upgrade?

- name: Make serving directory (0755 by default)
  file:
    path: "{{ maps_serve_path }}"
    state: directory
    # mode: 0755

- name: Make index file
  template:
    src: index.html.j2
    dest: "{{ maps_serve_path }}/index.html"

### maps.black ###

- name: Install maps.black.js
  copy:
    src: maps.black.js
    dest: "{{ maps_serve_path }}/maps.black.js"
    mode: "0644"

- name: Download the remaining basic maps.black javascript and styles (0644)
  include_tasks: download_large_file.yml
  vars:
    dest_base_path: "{{ maps_serve_path }}"
  with_items: "{{ maps_dot_black_js_and_styles }}"

- name: Get naturalearth6 from catalog
  include_tasks: download_from_catalog.yml
  vars:
    catalog_item: naturalearth6
    catalog_item_variant: "{{ maps_ne6_zoom }}"
    catalog_item_variant_name: maps_ne6_zoom
    symlink_name: "{{ maps_dot_black_naturalearth6_symlink_name }}"
    dest_base_path: "{{ maps_serve_path }}"

- name: Get vector from catalog
  include_tasks: download_from_catalog.yml
  vars:
    catalog_item: vector
    catalog_item_variant: "{{ maps_vector_zoom }}"
    catalog_item_variant_name: maps_vector_zoom
    symlink_name: "{{ maps_dot_black_osm_symlink_name }}"
    dest_base_path: "{{ maps_serve_path }}"

- name: Get satellite from catalog
  when: maps_satellite_zoom != "none"
  include_tasks: download_from_catalog.yml
  vars:
    catalog_item: satellite
    catalog_item_variant: "{{ maps_satellite_zoom }}"
    catalog_item_variant_name: maps_satellite_zoom
    symlink_name: "{{ maps_dot_black_satellite_symlink_name }}"
    dest_base_path: "{{ maps_serve_path }}"

- name: Remove unused satellite symlink
  when: maps_satellite_zoom == "none"
  file:
    path: "{{ maps_serve_path }}/{{ maps_dot_black_satellite_symlink_name }}"
    state: absent

# Unlike with satellite, if the user selects "none" for terrain, we download a dummy file
- name: Get terrain from catalog
  include_tasks: download_from_catalog.yml
  vars:
    catalog_item: terrain
    catalog_item_variant: "{{ maps_terrain_zoom }}"
    catalog_item_variant_name: maps_terrain_zoom
    symlink_name: "{{ maps_dot_black_terrain_symlink_name }}"
    dest_base_path: "{{ maps_serve_path }}"

- name: Initiate the extracts json
  copy:
    content: '{"regions": {}}'
    dest: "{{ maps_serve_path }}/{{ tile_extract.info_file }}"
    mode: "0644"
    force: false

- name: "Make sure maps_region_downloader is true if maps_preset_full_quality_regions has items"
  assert:
    that: maps_region_downloader or (maps_preset_full_quality_regions | length <= 0)
    fail_msg: "Error: you have maps_preset_full_quality_regions. Either set maps_region_downloader to true or unset maps_preset_full_quality_regions (this will not delete any already downloaded regions)."
    quiet: yes

- name: "Download preset full quality regions"
  # TODO - Is there a safer way to pass in item.name and item.bbox?
  shell: |
    set -euo pipefail
    {{ tile_extract.working_dir }}/tile-extract.py extract {{ item.name }} {{ item.bbox }} noninteractive
  args:
    executable: /bin/bash
  with_items: "{{ maps_preset_full_quality_regions }}"

### maplibre ###

- name: Download maplibre javascript and styles (0644)
  get_url:
    url: "{{ unpkg_url }}/{{ item.url_subpath }}"
    dest: "{{ maps_serve_path }}/{{ item.filename }}"
    checksum: "sha256:{{ item.sha256sum }}"
    mode: "0644"
    timeout: "{{ download_timeout }}"
  with_items: "{{ maplibre_js_and_styles }}"
