- name: Make index file
  template:
    src: index.html.j2
    dest: "{{ maps_serve_path }}/index.html"

### maps.black ###

- name: Install maps.black.js
  copy:
    src: maps.black.js
    dest: "{{ maps_serve_path }}/maps.black.js"
    mode: "0644"

- name: Download the remaining basic maps.black javascript and styles (0644)
  include_tasks: download_large_file.yml
  vars:
    dest_base_path: "{{ maps_serve_path }}"
  with_items: "{{ maps_dot_black_js_and_styles }}"

- name: Get naturalearth6 from catalog
  include_tasks: download_from_catalog.yml
  vars:
    catalog_item: naturalearth6
    catalog_item_config_var: maps_ne6_zoom
    symlink_name: "{{ maps_dot_black_naturalearth6_symlink_name }}"
    dest_base_path: "{{ maps_serve_path }}"

# This helps avoid silent errors transitioning between variable names. It can be deleted 2026/09/04.
- name: Error on deprecated maps_vector_quality
  assert:
    that: maps_vector_quality is not defined
    msg:
      - "'maps_vector_quality' has been renamed to 'maps_vector_zoom' with new valid values. Please update your"
      - "/etc/iiab/local_vars.yml and see https://github.com/iiab/iiab/blob/master/roles/maps/MAPS_CATALOG_DETAILS.md for valid values."


- name: Get vector from catalog
  include_tasks: download_from_catalog.yml
  vars:
    catalog_item: vector
    catalog_item_config_var: maps_vector_zoom
    symlink_name: "{{ maps_dot_black_osm_symlink_name }}"
    dest_base_path: "{{ maps_serve_path }}"

- name: Download fallback vector tiles
  include_tasks: download_large_file.yml
  when: maps_vector_zoom != maps_fallback_vector_zoom
  vars:
    dest_base_path: "{{ maps_serve_path }}"
    item: "{{ maps_catalog.data.vector[maps_fallback_vector_zoom | string] }}"

- name: Get satellite from catalog
  when: maps_satellite_zoom != "none"
  include_tasks: download_from_catalog.yml
  vars:
    catalog_item: satellite
    catalog_item_config_var: maps_satellite_zoom
    symlink_name: "{{ maps_dot_black_satellite_symlink_name }}"
    dest_base_path: "{{ maps_serve_path }}"

- name: Download fallback satellite tiles
  when: (maps_satellite_zoom != "none") and (maps_satellite_zoom != maps_fallback_satellite_zoom)
  include_tasks: download_large_file.yml
  vars:
    dest_base_path: "{{ maps_serve_path }}"
    item: "{{ maps_catalog.data.satellite[maps_fallback_satellite_zoom | string] }}"

- name: Remove unused satellite symlink
  when: maps_satellite_zoom == "none"
  file:
    path: "{{ maps_serve_path }}/{{ maps_dot_black_satellite_symlink_name }}"
    state: absent

# Unlike with satellite, if the user selects "none" for terrain, we download a dummy file
- name: Get terrain from catalog
  include_tasks: download_from_catalog.yml
  vars:
    catalog_item: terrain
    catalog_item_config_var: maps_terrain_zoom
    symlink_name: "{{ maps_dot_black_terrain_symlink_name }}"
    dest_base_path: "{{ maps_serve_path }}"

- name: Download fallback terrain tiles
  include_tasks: download_large_file.yml
  when: maps_terrain_zoom != maps_fallback_terrain_zoom
  vars:
    dest_base_path: "{{ maps_serve_path }}"
    item: "{{ maps_catalog.data.terrain[maps_fallback_terrain_zoom | string] }}"

# maps-update.py is used here but it can also be run independently. As we use
# it here, we take advantage of its handling of pmtiles zoom levels. It only
# partially handles symlink repairs for now so we still need to set symlinks
# by other means.
- name: "Final map configuration"
  shell: |
    set -euo pipefail
    {{ maps_tools.base_dir }}/maps-update.py
  args:
    executable: /bin/bash

- name: Initiate the extracts json
  copy:
    content: '{"regions": {}}'
    dest: "{{ maps_serve_path }}/{{ maps_tools.tile_extract.info_file }}"
    mode: "0644"
    force: false

- name: "Download preset full quality regions"
  # TODO - Is there a safer way to pass in item.name and item.bbox?
  shell: |
    set -euo pipefail
    {{ maps_tools.tile_extract.working_dir }}/tile-extract.py extract {{ item.name }} {{ item.bbox }} noninteractive
  args:
    executable: /bin/bash
  with_items: "{{ maps_preset_full_quality_regions }}"

### maplibre ###

- name: Download maplibre javascript and styles (0644)
  get_url:
    url: "{{ unpkg_url }}/{{ item.url_subpath }}"
    dest: "{{ maps_serve_path }}/{{ item.filename }}"
    checksum: "sha256:{{ item.sha256sum }}"
    mode: "0644"
    timeout: "{{ download_timeout }}"
  with_items: "{{ maplibre_js_and_styles }}"
