- name: Record (initial) disk space used
  shell: df -B1 --output=used / | tail -1
  register: df1


- name: Yarn | Remove leftover Yarn v1 apt sources (if upgrading from v1)
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/yarn.sources
    - /etc/apt/sources.list.d/dl_yarnpkg_com_debian.list

- name: Yarn | Enable corepack (ships with Node.js)
  shell: corepack enable

- name: Yarn | Install Yarn v2+ (Berry) via corepack
  shell: corepack prepare yarn@stable --activate


# RECORD Yarn AS INSTALLED

- name: Record (final) disk space used
  shell: df -B1 --output=used / | tail -1
  register: df2

- name: Add 'yarn_disk_usage = {{ df2.stdout | int - df1.stdout | int }}' to {{ iiab_ini_file }}
  ini_file:
    path: "{{ iiab_ini_file }}"    # /etc/iiab/iiab.ini
    section: yarn
    option: yarn_disk_usage
    value: "{{ df2.stdout | int - df1.stdout | int }}"

- name: "Set 'yarn_installed: True'"
  set_fact:
    yarn_installed: True

- name: "Add 'yarn_installed: True' to {{ iiab_state_file }}"
  lineinfile:
    path: "{{ iiab_state_file }}"    # /etc/iiab/iiab_state.yml
    regexp: '^yarn_installed'
    line: 'yarn_installed: True'
