- name: Reload systemd manager before resetting failed 'mosquitto' service state
  command: systemctl daemon-reload
  changed_when: false
  when: mosquitto_enabled

- name: Reset failed state before restarting 'mosquitto' systemd service
  command: systemctl reset-failed mosquitto
  register: mosquitto_reset_failed
  changed_when: false
  failed_when:
    - mosquitto_reset_failed.rc != 0
    - "'Unit mosquitto.service not loaded.' not in mosquitto_reset_failed.stderr"
  when:
    - mosquitto_enabled

- name: Enable & (Re)Start 'mosquitto' systemd service, if mosquitto_enabled
  systemd:
    daemon_reload: yes
    name: mosquitto
    enabled: yes
    state: restarted
  when: mosquitto_enabled

- name: Disable & Stop 'mosquitto' systemd service, if not mosquitto_enabled
  systemd:
    daemon_reload: yes
    name: mosquitto
    enabled: no
    state: stopped
  when: not mosquitto_enabled
