#!/bin/bash -x
# required to start loading XSCE 
set -e

apt-get update
apt-get upgrade
apt-get install -y mlocate vim emacs

cd /opt
mkdir schoolserver
cd schoolserver
git clone https://github.com/xsce/xsce --depth 1 
cd xsce

# install ansible using script
./scripts/ansible

./runansible

