#!/bin/bash -e
if [[ $(id -un) != "root" ]]; then
    echo -e "\nPlease run: sudo iiab-freshen\n"
    exit 1
fi

cd /opt/iiab/iiab
git checkout master
git pull --ff

export DEBIAN_FRONTEND=noninteractive

apt update

scripts/ansible

if [ -d /opt/iiab/iiab-admin-console ] && [ -f /etc/iiab/install-flags/iiab-admin-console-complete ]; then
    cd /opt/iiab/iiab-admin-console
    git checkout master
    if ! git pull -ff | grep 'Already up to date'; then
        echo -e "\nUpdating iiab-admin-console\n"
        ./install
    fi
fi

apt full-upgrade -y
apt autoremove -y

touch /etc/iiab/install-flags/iiab-refreshed
echo -e "\nIIAB install updated\n"
echo -e "\nREBOOTING NOW\n"
reboot
exit 0
