#!/bin/bash -e
if [ -d /opt/iiab/iiab-admin-console ] && [ -f /etc/iiab/install-flags/iiab-admin-console-complete ]; then
    cd /opt/iiab/iiab-admin-console
    git checkout master
    if ! git pull -ff | grep 'Already up to date'; then
        echo "Updating iiab-admin-console"
        ./install
    fi
fi
cd /opt/iiab/iiab
git checkout master
git pull --ff

scripts/ansible

apt update
apt -y full-upgrade
apt -y autoremove

touch /etc/iiab/install-flags/iiab-refreshed
echo "IIAB install updated"
echo "REBOOTING NOW"
reboot
exit 0
