#!/bin/bash -x
# required to start loading IIAB with ansible 2.3.X
set -e
echo "Installing --- Please Wait"
if [ -f /etc/fedora-release ];then
    VER=`grep VERSION_ID /etc/*elease | cut -d= -f2`
    dnf -y upgrade
    dnf -y install ansible patch
fi
if [ -f /etc/centos-release ];then
    yum -y upgrade
    yum -y install ca-certificates nss epel-release
    yum -y install ansible patch
fi

mkdir -p /opt/iiab
cd /opt/iiab
git clone https://github.com/iiab/iiab --depth 10
cd /opt/iiab/iiab

# PR in jvonau
PULL=6
wget https://patch-diff.githubusercontent.com/raw/jvonau/iiab/pull/$PULL.diff -o /tmp/$PULL.diff
patch -p 1 -i /tmp/$PULL.diff

./runansible
