#!/bin/bash -x
# required to start loading IIAB with ansible 2.3.X
set -e
echo "Installing --- Please Wait"
if [ -f /etc/fedora-release ];then
    VER=`grep VERSION_ID /etc/*elease | cut -d= -f2`
    URL=https://github.com/jvonau/iiab/blob/ansible/vars/fedora-$VER.yml
    dnf -y upgrade
    dnf -y install ansible
fi
if [ -f /etc/centos-release ];then
    yum -y upgrade
    yum -y install ca-certificates nss epel-release
    yum -y install ansible
fi

mkdir -p /opt/iiab
cd /opt/iiab
git clone https://github.com/iiab/iiab --depth 10
cd iiab/vars
wget $URL
cd ..
./runansible
