#!/bin/bash -x
# required to start loading IIAB with ansible 2.3.X
set -e
echo "Installing --- Please Wait"
if [ -f /etc/fedora-release ];then
    VER=`grep VERSION_ID /etc/*elease | cut -d= -f2`
    dnf -y upgrade
    dnf -y install ansible patch git
fi
if [ -f /etc/centos-release ];then
    yum -y upgrade
    yum -y install ca-certificates nss epel-release
    yum -y install ansible patch git
fi
if [ -f /etc/debian_version ] || [ grep -qi ubuntu /etc/lsb-release ] || grep -qi ubuntu /etc/os-release; then
    apt-get update
    # Install via package
    # apt-get update && \
    # apt-get install --no-install-recommends -y software-properties-common && \
    # apt-add-repository ppa:ansible/ansible && \
    # apt-get update && \
    # apt-get install -y ansible

    # Install required Python libs and pip
    apt-get install -y  python-setuptools python-pip python-yaml python-jinja2 python-httplib2 python-paramiko python-pkg-resources
    [ -n "$( apt-cache search python-keyczar )" ] && apt-get install -y  python-keyczar
    if ! apt-get install -y git ; then
      apt-get install -y git-core
    fi
    # Install Ansible module dependencies
    apt-get install -y bzip2 file findutils gzip mercurial procps subversion sudo tar debianutils unzip xz-utils zip python-selinux
    # If python-keyczar apt package does not exist, use pip
    [ -z "$( apt-cache search python-keyczar )" ] && sudo pip install python-keyczar
    pip install ansible==2.3
else
    echo 'WARN: Could not detect distro or distro unsupported'
    echo 'WARN: Trying to install ansible via pip without some dependencies'
    echo 'WARN: Not all functionality of ansible may be available'
fi

mkdir /etc/ansible/
echo -e '[local]\nlocalhost\n' > /etc/ansible/hosts

# Now grap the just iiab for now
mkdir -p /opt/iiab
cd /opt/iiab
git clone https://github.com/iiab/iiab --depth 10
cd /opt/iiab/iiab

# PR in jvonau
PULL=6
wget https://patch-diff.githubusercontent.com/raw/jvonau/iiab/pull/$PULL.diff -o /tmp/$PULL.diff
patch -p 1 -i /tmp/$PULL.diff

./runansible
