#!/bin/bash
# PR #
PULL=""
# iiab jv tm gh
# optional repo where the PR lives default iiab
USER=
# PR in jvonau
case $USER in
    jv)
    USER=jvonau
    ;;
    tm)
    USER=tim-moody
    ;;
    gh)
    USER=georgejhunt
    ;;
    *)
    USER=iiab
    ;;
esac
cd /opt/iiab/iiab
wget https://github.com/$USER/iiab/pull/$PULL.diff -o /tmp/$PULL.diff

echo "patching..."
patch -p 1 -i $PULL.diff
rm /tmp/$PULL.diff

