- name: Enable & Restart 'anki' systemd service, if anki_enabled
  systemd:
    name: anki
    daemon_reload: yes
    enabled: yes
    state: restarted
  when: anki_enabled

- name: Disable & Stop 'anki' systemd service, if not anki_enabled
  systemd:
    name: anki
    enabled: no
    state: stopped
  when: not anki_enabled


- name: Enable http://box{{ anki_url }} via NGINX, by installing {{ nginx_conf_dir }}/anki-nginx.conf from template
  template:
    src: anki-nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/anki-nginx.conf"    # /etc/nginx/conf.d
  when: anki_enabled

- name: Disable http://box{{ anki_url }} via NGINX, by removing {{ nginx_conf_dir }}/anki-nginx.conf
  file:
    path: "{{ nginx_conf_dir }}/anki-nginx.conf"    # /etc/nginx/conf.d
    state: absent
  when: not anki_enabled

- name: Restart 'nginx' systemd service
  systemd:
    name: nginx
    state: restarted
