# captive_portal_install: False
# captive_portal_enabled: False

# captiveportal_port: 9090  # only used when running capture-wsgi.py directly

# All above are set in: github.com/iiab/iiab/blob/master/vars/default_vars.yml
# If nec, change them by editing /etc/iiab/local_vars.yml prior to installing!
