#!/bin/bash
# turn on the flag which registers new USB sticks at root directory

sed -i -e's/^IIAB_USB_LIB_SHOW_ALL.*/IIAB_USB_LIB_SHOW_ALL=False/' /etc/iiab/iiab.env

udevadm trigger -t subsystems -s usb -c add
