# NOTE: I'm more than happy to change the variable or directory names to
# something more in line with IIAB expectations.

maps_dot_black_resources_url: https://v1.maps.black
maps_dot_black_assets_url: https://maps.black

naturalearth_openmaptiles: naturalearth-openmaptiles.pmtiles          # 85MB circa Sept 2025

maps_dot_black_path: "{{ content_base }}/www/maps-dot-black"    # /library/www/maps-dot-black
