# NOTE: I'm more than happy to change the variable or directory names to
# something more in line with IIAB expectations.

maps_dot_black_resources_url: https://v1.maps.black
maps_dot_black_assets_url: https://maps.black

maps_dot_black_path: "{{ content_base }}/www/maps-dot-black"    # /library/www/maps-dot-black

# TODO checksums for the non-tile assets (js, etc)
# TODO host our own assets and tiles? Because they may get updated which will break our checksums.

# (Relatively) Low-res, low size base map files
# File size circa Sept 2025
maps_dot_black_tiles:
  # Mostly borders, rivers, country names. 85MB
  naturalearth_openmaptiles:
    filename: naturalearth-openmaptiles.pmtiles
    checksum: sha256:5ff72ad4944fe64188802d45d5ee88c8c819c94d3b21eba8fae7b19a92a1cc3b

  # Mostly colors, topography, etc. 58M
  naturalearth6_NE2_HR_SR_W_DR_WEBP:
    filename: naturalearth6-NE2_HR_SR_W_DR-WEBP.pmtiles
    checksum: sha256:22b44759a3f4c7f6a6c7abdcc3dd48786ebbb96f9b3479e6692083e25021207b
