#!/bin/bash -x
# substitute our own server to catch OS connectivity checking URL's

systemctl stop apache2
systemctl stop captive-portal
echo address=/#/172.18.96.1 > /etc/dnsmasq.d/capture
/opt/iiab/captive-portal/capture-wsgi.py -d &
# write the pid just started
echo $! > /opt/iiab/captive-portal/pid
