# 2025-09-15: THESE TOO SHOULD BE FULLY DEPRECATED...

# UNMAINTAINED...
# xo_services
# activity_server
# ejabberd_xs
# idmgr
# dokuwiki
# ejabberd
# elgg

# LET'S DEPRECATE THESE SOON TOO...
# lokole

- name: "DISALLOW 'dhcpd_install' (deprecated var)"
  assert:
    that: dhcpd_install is undefined
    fail_msg: "DISALLOWED: 'dhcpd_install' (e.g. in /etc/iiab/local_vars.yml)"
    quiet: yes

- name: "DISALLOW 'named_install' (deprecated var)"
  assert:
    that: named_install is undefined
    fail_msg: "DISALLOWED: 'named_install:' (e.g. in /etc/iiab/local_vars.yml)"
    quiet: yes

- name: "DISALLOW 'wondershaper_install' (deprecated var)"
  assert:
    that: wondershaper_install is undefined
    fail_msg: "DISALLOWED: 'wondershaper_install:' (e.g. in /etc/iiab/local_vars.yml)"
    quiet: yes

- name: "DISALLOW 'dansguardian_install' (deprecated var)"
  assert:
    that: dansguardian_install is undefined
    fail_msg: "DISALLOWED: 'dansguardian_install:' (e.g. in /etc/iiab/local_vars.yml)"
    quiet: yes

- name: "DISALLOW 'kalite_install' (deprecated var)"
  when: iiab_base_ver is version('8.4', 'ge')
  assert:
    that: kalite_install is undefined
    fail_msg: "DISALLOWED: 'kalite_install: in /etc/iiab/local_vars.yml - Please remove both kalite_ entries"
    quiet: yes
