= Matomo README

https://matomo.org/[Matomo] is a web analytics alternative to Google Analytics, emphasizing privacy and data ownership, that you can use with https://internet-in-a-box.org[Internet-in-a-Box] (IIAB).

== Install it

Prior to installing Matomo with IIAB, the default URL (http://box.lan/matomo) can be customized in https://wiki.iiab.io/go/FAQ#What_is_local_vars.yml_and_how_do_I_customize_it.3F[/etc/iiab/local_vars.yml]

One way to do that is by changing these 2 lines:

----
iiab_hostname: box
iiab_domain: lan
----

Or, you can change the Matomo URL by putting your IIAB IP Address in a line like:

----
matomo_host_url: http://192.168.0.199
----

Either way, consider setting a Matomo username and password using lines like:

----
matomo_db_user: Admin
matomo_db_pass: changeme
----

Also ensure that your `/etc/iiab/local_vars.yml` contains these lines:

----
matomo_install: True
matomo_enabled: True
----

_Finally, continue to https://download.iiab.io[install IIAB], e.g. by running `sudo iiab`, until software installation is complete._

== Use it

Log in to your IIAB's full Matomo URL, e.g. http://box.lan/matomo, as arranged above.

Take a look at Matomo's official guides to further set this up: https://matomo.org/guides/

WARNING: Matomo won't show any traffic statistics until after 1 day or reboot (which are the events that trigger the log scraper!)

== Credits

Carl Wivagg
