name: '"02 min" Ansible Lint on Ubuntu 24.04'

on:
  push:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.j2'
      - '!.github/workflows/*'
  pull_request:  # needed to show up in Pull Request UI
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.j2'
      - '!.github/workflows/*'
  workflow_dispatch:

jobs:
  ansible-lint:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      #- name: Dump GitHub context (typically almost 500 lines)
      #  env:
      #    GITHUB_CONTEXT: ${{ toJSON(github) }}
      #  run: echo "$GITHUB_CONTEXT"

      - name: Check out repository code    # Clones repo onto github runner
        uses: actions/checkout@v6
      - name: Set up /opt/iiab/iiab    # Some steps to get ready for the install
        run: |
          mkdir /opt/iiab
          mv $GITHUB_WORKSPACE /opt/iiab
          mkdir $GITHUB_WORKSPACE    # OR SUBSEQUENT STEPS WILL FAIL
      - name: Install Ansible
        run: sudo /opt/iiab/iiab/scripts/ansible

      - name: Install ansible-lint
        run: pip install ansible-lint

      - name: Run ansible-lint
        run: ansible-lint
        working-directory: /opt/iiab/iiab
