name: 'Ansible modules/ Unit Tests'

on:
  push:
    paths:
      - 'modules/**'
  pull_request:
    paths:
      - 'modules/**'
  workflow_dispatch:

jobs:
  python-unittests:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "🎉 Triggered by a ${{ github.event_name }} event"
      - run: echo "🔎 Branch: ${{ github.ref }}"

      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Install ansible-core and pytest
        run: pip install ansible-core pytest

      - name: Run Python unit tests
        run: python -m pytest modules/tests/ -v
